/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"

@interface Question : NSObject <NSCoding> {
  NSString * __question;
  NSString * __answer;

  BOOL __question_isset;
  BOOL __answer_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=question, setter=setQuestion:) NSString * question;
@property (nonatomic, retain, getter=answer, setter=setAnswer:) NSString * answer;
#endif

- (id) initWithQuestion: (NSString *) question answer: (NSString *) answer;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) question;
- (void) setQuestion: (NSString *) question;
- (BOOL) questionIsSet;

- (NSString *) answer;
- (void) setAnswer: (NSString *) answer;
- (BOOL) answerIsSet;

@end

@protocol QuestionStore <NSObject>
- (NSArray *) getQuestions;  // throws TException
- (void) addQuestion: (Question *) question;  // throws TException
@end

@interface QuestionStoreClient : NSObject <QuestionStore> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface QuestionStoreProcessor : NSObject <TProcessor> {
  id <QuestionStore> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithQuestionStore: (id <QuestionStore>) service;
- (id<QuestionStore>) service;
@end

@interface quizlordConstants : NSObject {
}
@end
